FROM centos:7

# Install compile dependencies
RUN yum -y update && yum groupinstall -y 'Development Tools'
RUN yum -y install gcc gcc-c++ zlib-devel bzip2-devel bzip2 wget && yum clean all

WORKDIR /tmp/doss/

RUN GCC_VERSION=9.3.0 ;\
	wget https://ftp.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.gz ;\
	tar xzvf gcc-${GCC_VERSION}.tar.gz ;\
	mkdir obj.gcc-${GCC_VERSION} ;\
	cd gcc-${GCC_VERSION} ;\
	./contrib/download_prerequisites ;\
	cd ../obj.gcc-${GCC_VERSION} ;\
	../gcc-${GCC_VERSION}/configure --disable-multilib --enable-languages=c,c++ --program-suffix=-9 ;\
	make -j $(nproc) ;\
	make install

RUN rm -rf /tmp/doss
