FROM pdb-redo-builder-base:v1

ENV LDFLAGS=-static-libstdc++ CXX=g++-9 CCP4=/opt/ccp4 PKG_CONFIG_PATH=/usr/local/lib/pkgconfig CLIBD=$CCP4/lib/data

# Install mrc
RUN git clone https://github.com/mhekkel/mrc.git && cd mrc && ./configure && make && make install

# Install libcifpp
RUN git clone https://github.com/PDB-REDO/libcifpp.git && \
    cd libcifpp && ./configure --enable-resources && make -j $(nproc) && make install

# Install libzeep
RUN git clone https://github.com/mhekkel/libzeep.git && \
    cd libzeep && ./configure && make -j $(nproc) && make install

# Install libnewuoa
RUN git clone https://github.com/elsid/newuoa-cpp.git && \
    cd newuoa-cpp && \
	g++-9 -o libnewuoa.a -r -fpic -I include src/newuoa.cpp && \
	install libnewuoa.a /usr/local/lib/libnewuoa.a && \
	install include/newuoa.h /usr/local/include/

COPY newuoa.pc /usr/local/lib/pkgconfig

# Install libpdb-redo
RUN git clone https://github.com/PDB-REDO/libpdb-redo.git
COPY components.cif.gz libpdb-redo/data/
RUN cd libpdb-redo && ./configure --enable-resources && make -j $(nproc) && make install

# Clean up
RUN rm -rf /tmp/doss

CMD cd /tmp/build && ./configure --enable-resources && make
