FROM centos:7

# Install compile dependencies
RUN yum -y update && yum groupinstall -y 'Development Tools'

# Some more compile time dependencies, moved other yum actions here too upon request
RUN yum -y install gcc gcc-c++ zlib-devel bzip2-devel bzip2 wget openssl-devel \
	libatomic_ops-devel python2 python2-devel && \
	 yum clean all

WORKDIR /tmp/doss/

# Build a gcc with version GCC_VERSION = 9.3
# We only need the C++ compiler
RUN GCC_VERSION=9.3.0 ;\
	wget https://ftp.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.gz ;\
	tar xzvf gcc-${GCC_VERSION}.tar.gz ;\
	mkdir obj.gcc-${GCC_VERSION} ;\
	cd gcc-${GCC_VERSION} ;\
	./contrib/download_prerequisites ;\
	cd ../obj.gcc-${GCC_VERSION} ;\
	../gcc-${GCC_VERSION}/configure --disable-multilib --enable-languages=c,c++ --program-suffix=-9 ;\
	make -j $(nproc) ;\
	make install

# Install Boost
RUN curl -Lo boost_1_77_0.tar.bz2 https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.bz2 && \
	tar xvf boost_1_77_0.tar.bz2

# Use our own user-config.jam file to make sure the new compiler is used
COPY user-config.jam /tmp/doss/boost_1_77_0/

RUN cd boost_1_77_0/ && \
	./bootstrap.sh && \
	./b2 link=static --toolset=gcc-9 install --without-python

# Install a recent cmake

RUN wget https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3.tar.gz && \
	tar xf cmake-3.21.3.tar.gz && \
	cd cmake-3.21.3 && \
	./configure && \
	make && \
	make install

# That's done, now move on to building the CCP4 libraries used by PDB-REDO

# Install CCP4, partially. The .dockerignore file will avoid
# the inclusion of too many tools here.
COPY devtools /tmp/doss/ccp4/

# Our cj.rc file contains the settings required to build only static
# versions of the libraries we need
COPY cj.rc /tmp/doss/ccp4/

# Somehow, it looks like bazaar needs to be available and this has
# to be a separate step
RUN cd ccp4 && python2 ./cj build --clean bzr

# OK, lets do it
RUN cd ccp4 && python2 ./cj build --clean --no-network clipper gsl

# Hmmm, the monomer library was needed as well
RUN cd ccp4 && python2 ./cj build --clean --no-network monomers

# clean up the work directory.
RUN rm -rf /tmp/doss

# And that's all folks