FROM pdb-redo-boost:v1.75

# Install python
RUN yum -y install python2 python2-devel && yum clean all
RUN ln -sf `which python2` /usr/bin/python

WORKDIR /tmp/doss

# Install CCP4, partially
COPY devtools /tmp/doss/ccp4/
COPY cj.rc /tmp/doss/ccp4/

RUN cd ccp4 && python2 ./cj build --clean bzr
RUN cd ccp4 && python2 ./cj build --clean --no-network clipper
RUN cd ccp4 && python2 ./cj build --clean --no-network gsl

# clean up
RUN rm -rf /tmp/doss
