FROM pdb-redo-builder-base:v1

ENV LDFLAGS=-static-libstdc++ CXX=g++-9 CCP4=/opt/ccp4 PKG_CONFIG_PATH=/usr/local/lib/pkgconfig CLIBD=$CCP4/lib/data

# Install mrc
RUN git clone https://github.com/mhekkel/mrc.git && \
	cd mrc && \
	mkdir build && \
	cd build && \
	cmake .. -DCMAKE_CXX_COMPILER=g++-9 && \
	cmake --build . -j $(nproc) && \
	ctest . && \
	cmake --install .

# Install libcifpp
RUN git clone https://github.com/PDB-REDO/libcifpp.git
RUN cd libcifpp && \
	mkdir build && \
	cd build && \
	cmake .. -DCMAKE_CXX_COMPILER=g++-9 -DCIFPP_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr/local && \
	cmake --build . -j $(nproc) && \
	ctest . && \
	cmake --install .

# Install libzeep
RUN git clone https://github.com/mhekkel/libzeep.git && \
	cd libzeep && \
	mkdir build && \
	cd build && \
	cmake .. -DCMAKE_CXX_COMPILER=g++-9 -DZEEP_BUILD_TESTS=ON && \
	cmake --build . -j $(nproc) && \
	ctest . && \
	cmake --install .

# Install libnewuoa
RUN git clone https://github.com/elsid/newuoa-cpp.git && \
	cd newuoa-cpp && \
	mkdir build && \
	cd build && \
	sed -e's/ SHARED / STATIC /g' -i.bak ../CMakeLists.txt && \
	cmake .. && \
	cmake --build . -j $(nproc) && \
	cmake --install .

COPY newuoa.pc /usr/local/lib/pkgconfig

# Install libpdb-redo
RUN git clone https://github.com/PDB-REDO/libpdb-redo.git && \
	cd libpdb-redo && \
	mkdir build && \
	cd build && \
	cmake .. -DCMAKE_CXX_COMPILER=g++-9 -DPDB_REDO_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr/local && \
	cmake --build . -j $(nproc) && \
	ctest . --output-on-failure && \
	cmake --install .

# Clean up
RUN rm -rf /tmp/doss

CMD cd /tmp/build && mkdir build && cd build && cmake .. && cmake --build .  -j $(nproc)
