FROM pdb-redo-builder-base:v1

RUN yum -y install libatomic_ops-devel xz-devel && yum clean all

ENV LDFLAGS="-static-libgcc -static-libstdc++" CXX=g++-9 CCP4=/opt/ccp4 PKG_CONFIG_PATH=/usr/local/lib/pkgconfig CLIBD=$CCP4/lib/data

# Install mrc
RUN git clone https://github.com/mhekkel/mrc.git && \
	cd mrc && \
	mkdir build && \
	cd build && \
	cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-9 && \
	cmake --build . -j $(nproc) && \
	ctest . && \
	cmake --install .

# Clean up
RUN rm -rf /tmp/doss

CMD cd /tmp/build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build .  -j $(nproc)
